import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";
import Header from "./components/Header";
import Navigations from "./components/Navigations";
import "./globals.css";

const inriaSans = Inria_Sans({
  variable: "--font-inria-sans",
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inriaSans.className} px-4 pt-10 bg-gray-200 antialiased`}>
        <div className="max-w-[450px] mx-auto ">
          <Header />
          <Navigations />
          {children}
        </div>
      </body>
    </html>
  );
}
